name: Auto Update README Stats

on:
  schedule:
    # Runs every 12 hours (at 00:00 and 12:00 UTC)
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update README with latest stats
    
    permissions:
      contents: write
      actions: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
        
    - name: Update README stats
      run: |
        python .github/scripts/stats.py
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        
    - name: Generate Snake Animation
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: arpanchakraborty23
        outputs: |
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
    - name: Commit and push changes
      run: |
        git config --local user.email "arpanchakraborty500@gmail.com"
        git config --local user.name "arpanchakraborty23"
        git add .
        if git diff --staged --quiet; then
          echo "✅ No changes to commit"
        else
          git commit -m "🤖 Auto-update README stats - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi

  update-metrics:
    runs-on: ubuntu-latest
    name: Update GitHub metrics
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update GitHub Metrics
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        user: arpanchakraborty23
        template: classic
        base: header, activity, community, repositories, metadata
        config_timezone: Asia/Kolkata
        plugin_isocalendar: yes
        plugin_isocalendar_duration: half-year
        plugin_languages: yes
        plugin_languages_analysis_timeout: 15
        plugin_languages_categories: markup, programming
        plugin_languages_colors: github
        plugin_languages_limit: 8
        plugin_languages_recent_categories: markup, programming
        plugin_languages_recent_days: 14
        plugin_languages_recent_load: 300
        plugin_languages_sections: most-used
        plugin_languages_threshold: 0%
        plugin_activity: yes
        plugin_activity_days: 14
        plugin_activity_filter: all
        plugin_activity_limit: 5
        plugin_activity_load: 300
        plugin_activity_visibility: all
        filename: github-metrics.svg